### PR TITLE
added basic config files for babel, ts and webpack

### PR DESCRIPTION
**Pull request by otbe**
This PR adds some config files for https://github.com/CitadelJS/core/issues/4.

It supports:
- build (commonjs)
- typings
- tests (JS/TS) with sourcemap support
- "merged" coverage form sources

What have to be done in @citadel/XYZ?
- the base webpack configuration should be extended to add a output filename; the created webpack configuration should be named ```webpack.config.js```
- add devDeps (can't be shared :()
- add test/index.js that looks like:
```javascript
require('source-map-support').install();
var testsContext = require.context(".", true, /\.(ts|js)$/);
testsContext.keys().forEach(testsContext);
```
- I usually add these npm scripts:
```json
{
   "scripts": {
      "watch": "webpack -w",
      "build": "webpack",
      "build-tests": "webpack --config webpack-test.config.js",
      "test": "npm run build-tests && istanbul cover --print none --report json _mocha -- --full-trace generated/tests.js && remap-istanbul -i coverage/coverage.json > coverage/coverage-final.json && node scripts/generate-coverage.js text",
      "coverage-html": "npm run test && node scripts/generate-coverage.js html",
      "coverage-lcovonly": "npm run test && node scripts/generate-coverage.js lcovonly"
   }
}
```

### CODE REVIEW

**Comment by lholznagel** [comment]
Maybe the coverage script can be replaced with `nyc`?

**Comment by otbe** [comment]
Can't get nyc working yesterday evening. We need a build pipeline with two stages for src and tests (ts -> babel) and I would like to keep proper sourcemap support for tests and coverage. This is the reason for the little script because remap-Istanbul can not exclude patterns from the generated report. (issue pending) 

Please try to get it working I would love to kill this little script and some other things :)

**Comment by lholznagel** [comment]
Will take a look at it. Do you have a small test project? Never done something with babel.

**Comment by otbe** [comment]
Yes please look at my fork of inversify-express-utils and webpack related branch :)

**Comment by remojansen** [comment]
👍 looks goog for me. If we get nyc to work it could be even more simple :)

**Comment by lholznagel** [comment]
Currently got a weird error.
Testing the script
`nyc -r=text -r=lcov -i ts-node/register -e .ts mocha --require ts-node/register test/**/*.ts`
when I want to look at the coverage of a file in the browser I get the message that he does not find the file. But he is also looking on the wrong place

He looks at `/home/lholznagel/projects/my/CItadelJS/src/decorators.ts` but it must be
`/home/lholznagel/projects/my/CItadelJS/inversify-express-utils/src/decorators.ts`
so he completly ignores the folder `inversify-express-utils`

**Comment by lholznagel** [comment]
Sorry pressed the wrong comment button

**Comment by jhuntoo** [comment]
LGTM

**Comment by lholznagel** [comment]
LGTM
Think this can than be merged?

**Comment by remojansen** [comment]
:+1:

**Pull request merged**
