### PR TITLE
added tslint config

### PR DESCRIPTION
**Pull request by lholznagel**
Added the tslint config.
It is based on the [recommended ruleset from microsoft](https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/recommended_ruleset.js).

Discussed in [issue#11](https://github.com/CitadelJS/core/issues/11#issuecomment-231004963)

Sometimes the config will be a little bit annoying because it seems to be very hard configured.

### CODE REVIEW

**Comment by remojansen** [comment]
:+1:

**Comment by lholznagel** [comment]
Found one problem:
`"export-name": true`

here is a short example: when we export something called: `export class Example` we need to name our file `Example`. Don´t know about you but I name my files usually `example`.

**Comment by jhuntoo** [comment]
I agree with @lholznagel, for some reason in typescript i like the freedom of not having the "class name must match the filename" rule (but in c#/java i do prefer it). I guess because it's fairly common to have multiple exports in a single file in typescript.

**Comment by lholznagel** [comment]
Okay, how about we set it to false?

**Comment by remojansen** [comment]
:+1: to allow file name to have a name not equals to class name

**Comment by lholznagel** [comment]
another one. The config `align` is really annoying. Neither atom or vscode get the code formatted like tslint wants to, and I don´t know how tslint wants it to look like

**Comment by otbe** [comment]
Some thoughts about ```tslint.json```

- ```export-name``` only applies if there is only one named export. So multiple exports aren't a problem. In general I like 
```
import { Servcie } from 'Service';
```
more than 
```
import { Service } from 'service'; 
// or 
import { Service } from 'my-service'; 
```
But thats also fine 👍 
- ```interface-name``` is set to true which will lead to ```IDependenyProvider```... I prefer no capitalized I in interface names. Any thoughts?
- ```no-any``` is set to true. I would change this and introduce "noImplicitAny" to ```tsconfig.json```. This will give us full control over types. (Yeah any is eval, but sometimes needed :))
- ```align``` sounds good to me. Basically its:

Okay:
bildschirmfoto 2016-07-08 um 19 45 53

Okay:
bildschirmfoto 2016-07-08 um 19 46 02

Error:
bildschirmfoto 2016-07-08 um 19 46 27
- ```member-access``` I really hate it. Every function or field with ```public``` is a bit overkill. But thats personally taste...
- ```max-line-length``` grrr...but okay :D

**Comment by remojansen** [comment]
I agree with @otbe in all the points.

**Comment by lholznagel** [comment]
Any doubts against the config? When not I think we can merge it

**Comment by lholznagel** [comment]
So changed
- `member-access` from true to false
- `no-any` from true to false
- `interface-name` from true to false
- `max-line-length` from true to false

`export-name` and `align` I already set to false

**Comment by otbe** [comment]
LGTM

**Comment by remojansen** [comment]
:+1: Nice to see this merge

**Pull request merged**
